{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nkp-academy.fullname" . }}-secret
  labels:
    {{- include "nkp-academy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
